
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 07 10:19:32 CST 2022
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT_COMA = 11;
  public static final int CONJ = 6;
  public static final int EOF = 0;
  public static final int CONJUNTO = 3;
  public static final int SEPARADOR = 7;
  public static final int ASIGNACION = 12;
  public static final int error = 1;
  public static final int DOS_PTS = 10;
  public static final int FRASE = 5;
  public static final int LLAVE_CIERRE = 9;
  public static final int EXPRESION = 4;
  public static final int LLAVE_APERTURA = 8;
  public static final int IDENTIFICADOR = 2;
}

