
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package ocl1_proyecto1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT_COMA = 11;
  public static final int CONJ = 6;
  public static final int EOF = 0;
  public static final int CONJUNTO = 3;
  public static final int SEPARADOR = 7;
  public static final int ASIGNACION = 12;
  public static final int error = 1;
  public static final int DOS_PTS = 10;
  public static final int FRASE = 5;
  public static final int LLAVE_CIERRE = 9;
  public static final int EXPRESION = 4;
  public static final int LLAVE_APERTURA = 8;
  public static final int IDENTIFICADOR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "CONJUNTO",
  "EXPRESION",
  "FRASE",
  "CONJ",
  "SEPARADOR",
  "LLAVE_APERTURA",
  "LLAVE_CIERRE",
  "DOS_PTS",
  "PT_COMA",
  "ASIGNACION"
  };
}

